config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_aiphi-theme.el:
    dst: ~/.emacs.d/themes/aiphi-theme.el
    src: emacs.d/themes/aiphi-theme.el
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_battery:
    dst: ../.i3/blocks/battery
    src: i3/blocks/battery
  f_blocks.conf:
    dst: ../.i3/blocks.conf
    src: i3/blocks.conf
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_config:
    dst: ~/.i3/config
    src: i3/config
  f_cpu:
    dst: ../.i3/blocks/cpu
    src: i3/blocks/cpu
  f_emacs:
    dst: ~/.emacs
    src: emacs
  f_form-mode.el:
    dst: ~/.emacs.d/modes/form-mode.el
    src: emacs.d/modes/form-mode.el
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_jl-builtin.el:
    dst: ~/.emacs.d/config/jl-builtin.el
    src: emacs.d/config/jl-builtin.el
  f_jl-c-cpp.el:
    dst: ~/.emacs.d/config/jl-c-cpp.el
    src: emacs.d/config/jl-c-cpp.el
  f_jl-custom-set-variables.el:
    dst: ~/.emacs.d/custom-set/jl-custom-set-variables.el
    src: emacs.d/custom-set/jl-custom-set-variables.el
  f_jl-extra.el:
    dst: ~/.emacs.d/config/jl-extra.el
    src: emacs.d/config/jl-extra.el
  f_jl-form.el:
    dst: ~/.emacs.d/config/jl-form.el
    src: emacs.d/config/jl-form.el
  f_jl-functions.el:
    dst: ~/.emacs.d/config/jl-functions.el
    src: emacs.d/config/jl-functions.el
  f_jl-keybindings.el:
    dst: ~/.emacs.d/config/jl-keybindings.el
    src: emacs.d/config/jl-keybindings.el
  f_jl-latex-mode.el:
    dst: ~/.emacs.d/config/jl-latex-mode.el
    src: emacs.d/config/jl-latex-mode.el
  f_jl-lisp-mode.el:
    dst: ~/.emacs.d/config/jl-lisp-mode.el
    src: emacs.d/config/jl-lisp-mode.el
  f_jl-modeline.el:
    dst: ~/.emacs.d/config/jl-modeline.el
    src: emacs.d/config/jl-modeline.el
  f_jl-prettify-symbols.el:
    dst: ~/.emacs.d/config/jl-prettify-symbols.el
    src: emacs.d/config/jl-prettify-symbols.el
  f_kblayout:
    dst: ../.i3/blocks/kblayout
    src: i3/blocks/kblayout
  f_lock_screen.sh:
    dst: ~/bin/lock_screen.sh
    src: bin/lock_screen.sh
  f_smart-mode-line-aiphi.el:
    dst: ~/.emacs.d/themes/smart-mode-line-aiphi.el
    src: emacs.d/themes/smart-mode-line-aiphi.el
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_wifi:
    dst: ../.i3/blocks/wifi
    src: i3/blocks/wifi
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  jls-minion:
    dotfiles:
    - f_bashrc
    - f_xresources
    - f_config
    - f_gitconfig
    - f_compton.conf
    - f_termite_config
    - f_lock_screen.sh
    - f_emacs
    - f_jl-builtin.el
    - f_jl-c-cpp.el
    - f_jl-extra.el
    - f_jl-form.el
    - f_jl-functions.el
    - f_jl-keybindings.el
    - f_jl-latex-mode.el
    - f_jl-lisp-mode.el
    - f_jl-modeline.el
    - f_jl-prettify-symbols.el
    - f_aiphi-theme.el
    - f_smart-mode-line-aiphi.el
    - f_form-mode.el
    - f_jl-custom-set-variables.el
    - f_blocks.conf
    - f_battery
    - f_cpu
    - f_kblayout
    - f_wifi
  jureca:
    dotfiles:
    - f_bashrc
    - f_gitconfig
