config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_config:
    dst: ~/.i3/config
    src: i3/config
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_i3status_config:
    dst: ~/.config/i3status/config
    src: config/i3status/config
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  jls-minion:
    dotfiles:
    - f_bashrc
    - f_xresources
    - f_config
    - f_gitconfig
    - f_i3status_config
    - f_compton.conf
    - f_termite_config
