separator_block_width=15
# block_dir=$HOME/.i3/blocks

[keyboard_layout]
label=
command=$HOME/.i3/blocks/kblayout
interval=5
separator=true

[disk]
label=
command=/usr/lib/i3blocks/disk
#instance=/mnt/data
interval=30
separator=false

[cpu_usage]
label=
command=$HOME/.i3/blocks/cpu
interval=2
separator=false

[temperature]
label=
interval=10
command=/usr/lib/i3blocks/temperature
separator=true

[wifi]
label=wifi
command=$HOME/.i3/blocks/wifi
instance=wlp3s0
interval=10
separator=true

[battery]
command=$HOME/.i3/blocks/battery
interval=10

[time]
command= date '+%Y-%m-%d / %H:%M'
label=
interval=1
