;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Customize Emacs prettifications
;;;
;;; Author: Jan-Lukas Wynen
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defconst jl/prettify-math-alist
  '(
    (">=" . ?≥)
    ("<=" . ?≤)
    ("!=" . ?≠)
    ("in" . ?∈)
    )
  )

(defconst jl/prettify-greek-alist
  '(
    ("epsilon" . ?ε)
    ("Epsilon" . ?Ε)
    ("rho" . ?ρ)
    ("Rho" . ?Ρ)
    ("tau" . ?τ)
    ("Tau" . ?Τ)
    ("zeta" . ?ζ)
    ("Zeta" . ?Ζ)
    ("theta" . ?θ)
    ("Theta" . ?Θ)
    ("iota" . ?ι)
    ("Iota" . ?Ι)
    ("omicron" . ?ο)
    ("Omicron" . ?Ο)
    ("pi" . ?π)
    ("Pi" . ?Π)
    ("alpha" . ?α)
    ("Alpha" . ?Α)
    ("sigma" . ?σ)
    ("Sigma" . ?Σ)
    ("delta" . ?δ)
    ("Delta" . ?Δ)
    ("phi" . ?φ)
    ("Phi" . ?Φ)
    ("gamma" . ?γ)
    ("Gamma" . ?Γ)
    ("eta" . ?η)
    ("Eta" . ?Η)
    ("xi" . ?ξ)
    ("Xi" . ?Ξ)
    ("kappa" . ?κ)
    ("Kappa" . ?Κ)
    ("lambda" . ?λ)
    ("Lambda" . ?Λ)
    ("upsilon" . ?υ)
    ("Upsilon" . ?Υ)
    ("chi" . ?χ)
    ("Chi" . ?Χ)
    ("psi" . ?ψ)
    ("Psi" . ?Ψ)
    ("omega" . ?ω)
    ("Omega" . ?Ω)
    ("beta" . ?β)
    ("Beta" . ?Β)
    ("nu" . ?ν)
    ("Nu" . ?Ν)
    ("mu" . ?μ)
    ("Mu" . ?Μ)
    )
  )
